language: go

go:
  - 1.13.x

evn: 
  - GO111MODULE=on
  
install: 
  - go get -v

befor_deploy: make release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN 
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    repo: oldthreefeng/db-doc
    tags: true
